import { chromium } from 'playwright';
import fs from 'node:fs';
import assert from 'node:assert/strict';
(async()=>{const ledger=JSON.parse(fs.readFileSync(new URL('../../DEMO-ACCOUNTS.local.md', import.meta.url),'utf8').match(/```json\n([\s\S]*?)\n```/)[1]);const browser=await chromium.launch({headless:true,...(process.env.QA_BROWSER_PATH ? { executablePath: process.env.QA_BROWSER_PATH } : {})});try{const page=await browser.newPage();let failing=false;let calls=[];const date='2026-09-22T09:00:00.000Z';const id='11111111-1111-4111-8111-111111111111';const row={id,title:'Backend record outside cached list',category:'furniture',created_at:date,owner_id:id,hidden:false,state:'open',owner_name:'Server Owner',owner_company:'Server Company',offer_count:7};
await page.route('**/api/db/rpc/admin_stats',async route=>{const r=await route.fetch();const j=await r.json();await route.fulfill({response:r,json:{...j,adminApiVersion:1}})});
await page.route('**/api/db/rpc/admin_search_requests',async route=>{const args=route.request().postDataJSON();calls.push(args);if(failing)return route.fulfill({status:500,json:{message:'QA mock error'}});await route.fulfill({json:{items:[{...row,title:args.p_cursor?'Second backend record':row.title}],hasMore:!args.p_cursor,nextCursor:args.p_cursor?null:{created_at:date,id,asOf:date},filteredTotal:2,asOf:date}})});
await page.route('**/api/db/rpc/admin_search_users',async route=>{const args=route.request().postDataJSON();calls.push(args);await route.fulfill({json:{items:[{id,name:'Server user',company:'Server-only company',role:'company',city:'tbilisi',phone:'+995555111222',email:'fixture@example.test',verified:true,blocked:false,created_at:date}],hasMore:false,nextCursor:null,filteredTotal:1,asOf:date}})});
await page.route('**/api/db/rpc/admin_list_audit',route=>route.fulfill({json:{items:[{id,actor_id:id,target_type:'request',target_id:id,action:'request.hide',reason:'Test durable event',old_flags:{hidden:false},new_flags:{hidden:true},created_at:date}],hasMore:false,nextCursor:null,filteredTotal:1,asOf:date}}));
await page.goto('http://localhost:3000/account/');await page.locator('#login-email').fill('demo-admin@meetany.ge');await page.locator('#login-password').fill(ledger.accounts.admin.password);await page.locator('form button[type=submit]').click();await page.locator('#login-email').waitFor({state:'hidden',timeout:60000});await page.goto('http://localhost:3000/admin/');await page.getByText(row.title,{exact:true}).waitFor();await page.getByText('Server Company',{exact:true}).waitFor();await page.getByRole('button',{name:'შემდეგი გვერდი'}).click();await page.getByText('Second backend record',{exact:true}).waitFor();assert(new URL(page.url()).searchParams.has('cursor'));await page.getByRole('button',{name:'პირველი გვერდი',exact:true}).click();await page.getByText(row.title,{exact:true}).waitFor();assert(!new URL(page.url()).searchParams.has('cursor'));await page.getByRole('button',{name:'შემდეგი გვერდი'}).click();await page.getByText('Second backend record',{exact:true}).waitFor();await page.getByLabel('ძიება',{exact:true}).fill('unrelated-local-query');await page.getByText(row.title,{exact:true}).waitFor();assert(!new URL(page.url()).searchParams.has('cursor'));assert(calls.some(c=>c.p_q==='unrelated-local-query'));await page.getByRole('link',{name:'მომხმარებლები',exact:true}).click();await page.getByText('Server-only company',{exact:false}).waitFor();await page.getByLabel('როლი',{exact:true}).selectOption('company');await page.waitForURL(/role=company/);await page.getByLabel('სტატუსი',{exact:true}).selectOption('verified');await page.getByText('Server-only company',{exact:false}).waitFor();assert(calls.some(c=>c.p_role==='company'&&c.p_verified===true&&c.p_blocked===false));await page.getByRole('link',{name:'მოქმედებების ჟურნალი',exact:true}).click();await page.getByText('Test durable event',{exact:true}).waitFor();await page.setViewportSize({width:320,height:850});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'/tmp/admin-audit-v1-320.png',fullPage:true});failing=true;await page.goto('http://localhost:3000/admin/?tab=requests');await page.getByRole('button',{name:'ხელახლა ცდა',exact:true}).waitFor();assert.equal(await page.locator('tbody').count(),0);failing=false;await page.getByRole('button',{name:'ხელახლა ცდა',exact:true}).click();await page.getByText(row.title,{exact:true}).waitFor();console.log('PASS mocked admin v1 server rows, cursor, reset, server filter authority, audit, retry, 320px');}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
