// Real local API + RLS roundtrip. Only auth uses a fixture issuer. Run from web,
// with Next at 127.0.0.1:3201 and NEON_AUTH_BASE_URL=http://127.0.0.1:4201.
import fs from 'node:fs';
import http from 'node:http';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import nextEnv from '@next/env';
import pg from 'pg';
import { generateKeyPair, exportJWK, SignJWT } from 'jose';
import { chromium } from 'playwright';
nextEnv.loadEnvConfig(process.cwd());
const origin=process.env.QA_ORIGIN||'http://127.0.0.1:3201',auth=process.env.NEON_AUTH_BASE_URL,dsn=process.env.MEETANY_LOCAL_DATABASE_URL;
for(const url of [origin,auth,dsn])assert(url&&['localhost','127.0.0.1'].includes(new URL(url).hostname),'Loopback endpoints only');
assert(!process.env.DATABASE_URL,'Remove production DATABASE_URL');assert.match(new URL(dsn).pathname,/^\/meetany_preview_\d+$/);assert.equal(new URL(origin).hostname,new URL(auth).hostname);
const sql=new pg.Client({connectionString:dsn});await sql.connect();
const ids=Object.fromEntries(['buyer','supplier','other','admin'].map(role=>[role,crypto.randomUUID()])),requests=[crypto.randomUUID(),crypto.randomUUID(),crypto.randomUUID()];
const users=Object.fromEntries(Object.entries(ids).map(([role,id])=>[id,{id,name:{buyer:'Coffee House QA',supplier:'Print Solutions QA',other:'Eco Print QA',admin:'QA Admin'}[role],email:`deals-${id}@example.test`,role:'authenticated',emailVerified:true}]));
const {privateKey,publicKey}=await generateKeyPair('EdDSA'),jwk={...await exportJWK(publicKey),kid:crypto.randomUUID(),alg:'EdDSA',use:'sig'};
const token=id=>new SignJWT(id?{...users[id],sub:id}:{role:'anonymous'}).setProtectedHeader({alg:'EdDSA',kid:jwk.kid}).setIssuer(auth).setAudience(new URL(auth).origin).setIssuedAt().setExpirationTime('1h').sign(privateKey);
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Content-Type','application/json');if(req.method==='OPTIONS'){res.end();return;}const raw=/(?:^|; )qa-deal-user=([^;]+)/.exec(req.headers.cookie||'')?.[1],id=users[raw]?raw:null;
if(req.url==='/.well-known/jwks.json')res.end(JSON.stringify({keys:[jwk]}));else if(req.url==='/get-session')res.end(JSON.stringify(id?{user:users[id]}:null));else if(['/token','/token/anonymous'].includes(req.url))res.end(JSON.stringify({token:await token(req.url==='/token'?id:null)}));else{res.statusCode=404;res.end('{}');}});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(Number(new URL(auth).port),new URL(auth).hostname,resolve);});
const output='qa/shots/deals-local';fs.mkdirSync(output,{recursive:true});const report={checks:[],views:[],pageErrors:[],consoleErrors:[],expectedHttpErrors:[],cleanup:false,mutations:[]};let browser;const pages=[];
async function rpc(id,fn,args={},code){const r=await fetch(`${origin}/api/db/rpc/${fn}`,{method:'POST',headers:{Authorization:`Bearer ${await token(id)}`,'Content-Type':'application/json'},body:JSON.stringify(args)}),data=await r.json();if(code){assert(!r.ok);assert.match(JSON.stringify(data),new RegExp(code));}else assert(r.ok,`${fn}: ${JSON.stringify(data)}`);return data;}
async function pageFor(id){const c=await browser.newContext({viewport:{width:1200,height:1000},reducedMotion:'reduce'});if(id)await c.addCookies([{name:'qa-deal-user',value:id,url:auth}]);await c.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort('blockedbyclient'));const p=await c.newPage();pages.push(p);p.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});p.on('response',r=>{if(r.status()>=400)report.expectedHttpErrors.push({url:r.url().split('/').at(-1),status:r.status()});if(/confirm_deal_terms|propose_deal_terms|advance_deal/.test(r.url()))report.mutations.push({url:r.url().split('/').at(-1),status:r.status(),args:r.request().postDataJSON()});});p.setDefaultTimeout(20000);p.on('pageerror',e=>report.pageErrors.push(e.message));return p;}
async function go(p,path,heading){await p.goto(origin+path,{waitUntil:'domcontentloaded'});await p.getByRole('heading',{level:1,name:heading,exact:true}).first().waitFor({timeout:60000});}
async function shots(p,name){for(const width of [1200,390,1440]){await p.setViewportSize({width,height:1000});await p.evaluate(async()=>{await document.fonts.ready;window.scrollTo(0,0);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});await p.waitForTimeout(150);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${name}@${width} overflow`);await p.screenshot({path:`${output}/${name}-${width}.png`,fullPage:true,animations:'disabled'});report.views.push(`${name}-${width}`);}await p.setViewportSize({width:1200,height:1000});}
const button=(p,name)=>p.getByRole('button',{name,exact:true}),getDeal=(id,deal)=>rpc(id,'get_deal',{p_deal_id:deal});
try{
let n=0;for(const [role,id] of Object.entries(ids)){await sql.query('insert into neon_auth."user"(id,name,email,"emailVerified") values($1,$2,$3,true)',[id,users[id].name,users[id].email]);await rpc(id,'complete_profile',{p_role:['supplier','other'].includes(role)?'company':'client',p_name:users[id].name,p_company:users[id].name,p_phone:`+995 588 ${String(Date.now()).slice(-3)} ${String(++n).padStart(3,'0')}`,p_city:'tbilisi',p_industry:['supplier','other'].includes(role)?'other':null});}
await sql.query('update public.profiles set verified=true where id=any($1::uuid[])',[[ids.supplier,ids.other]]);await sql.query("update public.profiles set role='admin' where id=$1",[ids.admin]);
for(const id of requests)await sql.query("insert into public.requests(id,owner_id,title,body,category,city,quantity,unit) values($1,$2,'ბრენდირებული ქაღალდის ჭიქები','გვჭირდება ბრენდირებული ქაღალდის ჭიქების დამზადება და მიწოდება თბილისში.','other','tbilisi',2000,'pcs')",[id,ids.buyer]);
const offerArgs={p_request_id:requests[0],p_body:'სრულფერადი ბეჭდვა, ხარისხიანი ქაღალდი და მიწოდება თბილისში.',p_price:1.1,p_price_type:'unit',p_vat_included:true,p_delivery_days:10,p_delivery_included:true};
const offer=await rpc(ids.supplier,'send_offer',offerArgs);await rpc(ids.supplier,'set_offer_terms',{p_offer_id:offer.id,p_payment_terms:'50% წინასწარ · 50% მიწოდებისას',p_valid_until:new Date(Date.now()+86400000*14).toISOString().slice(0,10),p_commercial_terms:['სრულფერადი ბეჭდვა','FSC ქაღალდი','მიწოდება თბილისში'],p_expected_updated_at:offer.updated_at});await rpc(ids.other,'send_offer',{...offerArgs,p_price:2000,p_price_type:'total',p_delivery_days:7});
const comparison=await rpc(ids.buyer,'compare_offers',{p_request_id:requests[0]});assert.equal(Number(comparison.find(o=>o.id===offer.id).total_gel),2200);assert.equal(comparison.filter(o=>o.best_price).length,1);await rpc(ids.supplier,'compare_offers',{p_request_id:requests[0]},'MA901');report.checks.push('Server total/ranking and sealed comparison');
browser=await chromium.launch({headless:true,executablePath:process.env.QA_BROWSER_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const buyer=await pageFor(ids.buyer),supplier=await pageFor(ids.supplier),outsider=await pageFor(ids.other),admin=await pageFor(ids.admin),guest=await pageFor();
// Exercise the real RequestView mapper and two-RPC standalone form without shared-browser auth.
await go(supplier,`/requests/view/?id=${requests[0]}`,'ბრენდირებული ქაღალდის ჭიქები');
await supplier.getByText('50% წინასწარ · 50% მიწოდებისას',{exact:true}).waitFor();
await supplier.getByText('სრულფერადი ბეჭდვა · FSC ქაღალდი · მიწოდება თბილისში',{exact:true}).waitFor();
await shots(supplier,'request-offer-terms');
await button(supplier,'შეთავაზების რედაქტირება').click();
await supplier.locator('#of-paymentTerms').waitFor();
assert.equal(await supplier.locator('#of-paymentTerms').inputValue(),'50% წინასწარ · 50% მიწოდებისას');
assert.equal(await supplier.locator('#of-validUntil').inputValue(),new Date(Date.now()+86400000*14).toISOString().slice(0,10));
await shots(supplier,'request-offer-edit');
await go(supplier,`/requests/view/?id=${requests[2]}`,'ბრენდირებული ქაღალდის ჭიქები');
await supplier.getByRole('link',{name:'შეთავაზების მომზადება',exact:true}).click();
const form=supplier.getByRole('form',{name:'შეთავაზების ფორმა'});await form.waitFor();
await supplier.locator('#of-body').fill('ადგილობრივი QA შეთავაზება რეალური შენახვისა და გამეორების შესამოწმებლად.');
await supplier.locator('#of-paymentTerms').fill('გადახდა მიწოდებისას');
await supplier.locator('#of-commercialTerms').fill('შეფუთვა');
await shots(supplier,'offer-initial');
let sendAttempts=0,termsAttempts=0;
await supplier.route('**/rpc/send_offer',r=>{sendAttempts++;return r.continue();});
await supplier.route('**/rpc/set_offer_terms',r=>{termsAttempts++;return termsAttempts===1?r.fulfill({status:400,json:{message:'MA902: Local QA terms rejected'}}):r.continue();});
await button(form,'შეთავაზების გაგზავნა').click();
await button(form,'პირობების შენახვის გამეორება').waitFor();
assert(new URL(supplier.url()).pathname.startsWith('/offers/new'));
assert.equal(await supplier.locator('#of-paymentTerms').inputValue(),'გადახდა მიწოდებისას');
await shots(supplier,'offer-rpc2-failure');
await button(form,'პირობების შენახვის გამეორება').click();
await supplier.waitForURL(`**/requests/view/?id=${requests[2]}`);
await supplier.getByText('გადახდა მიწოდებისას',{exact:true}).waitFor();
assert.equal(sendAttempts,1);assert.equal(termsAttempts,2);
const persisted=await sql.query('select payment_terms,commercial_terms from public.offers where request_id=$1',[requests[2]]);
assert.equal(persisted.rowCount,1);assert.equal(persisted.rows[0].payment_terms,'გადახდა მიწოდებისას');assert.deepEqual(persisted.rows[0].commercial_terms,['შეფუთვა']);
await supplier.unroute('**/rpc/send_offer');await supplier.unroute('**/rpc/set_offer_terms');
await supplier.reload();await supplier.getByText('გადახდა მიწოდებისას',{exact:true}).waitFor();
report.checks.push('RequestView renders persisted terms and hydrates existing edit form');
report.checks.push('Standalone RPC2 failure retains form; one explicit retry saves terms without duplicate send');
await go(buyer,`/requests/compare/?id=${requests[0]}`,'ბრენდირებული ქაღალდის ჭიქები');await button(buyer,'არჩევა').first().waitFor();await shots(buyer,'compare-offers');await buyer.getByLabel('მაქსიმალური ფასი').fill('2100');assert.equal(await button(buyer,'არჩევა').count(),1);await buyer.getByLabel('მაქსიმალური ფასი').fill('');
await buyer.locator('main article').filter({hasText:'Print Solutions QA'}).getByRole('button',{name:'არჩევა',exact:true}).click();
const shown=comparison.find(o=>o.id===offer.id);await rpc(ids.supplier,'set_offer_terms',{p_offer_id:offer.id,p_payment_terms:shown.payment_terms,p_valid_until:shown.valid_until,p_commercial_terms:shown.commercial_terms,p_expected_updated_at:shown.updated_at});
await button(buyer.locator('#choose'),'შეთავაზების არჩევა').click();await buyer.getByRole('alert').filter({hasText:'პირობები შეიცვალა'}).waitFor();await buyer.locator('#choose').waitFor({state:'hidden'});report.checks.push('Selection MA904 closes confirmation and rereads before explicit reselection');
await buyer.locator('main article').filter({hasText:'Print Solutions QA'}).getByRole('button',{name:'არჩევა',exact:true}).click();await button(buyer.locator('#choose'),'შეთავაზების არჩევა').click();await buyer.waitForURL(/\/deals\/view\/\?id=/,{timeout:30000});const dealId=new URL(buyer.url()).searchParams.get('id');let deal=await getDeal(ids.buyer,dealId);assert.equal(deal.stage,'selected');assert.equal(deal.offer_id,offer.id);await buyer.getByRole('heading',{level:1,name:'მომწოდებელი არჩეულია',exact:true}).waitFor();await buyer.locator('main a[href^="tel:"]').waitFor();await shots(buyer,'deal-selected');assert.equal((await rpc(ids.buyer,'get_deal_contact',{p_deal_id:dealId}))[0].id,ids.supplier);await rpc(ids.other,'get_deal_contact',{p_deal_id:dealId},'MA901');report.checks.push('UI selection navigates to returned deal; contact privacy');
await button(buyer,'დეტალების განხილვა').click();await buyer.getByRole('heading',{level:1,name:'დეტალების განხილვა',exact:true}).waitFor();await buyer.getByLabel('შეტყობინება',{exact:true}).fill('გამარჯობა, მიწოდება 8 დღეში შევათანხმოთ?');await button(buyer,'გაგზავნა').click();await buyer.getByRole('log').getByText('გამარჯობა, მიწოდება 8 დღეში შევათანხმოთ?',{exact:false}).waitFor();await shots(buyer,'deal-discuss');
await button(buyer,'პირობების შეთავაზება').click();await buyer.locator('input[name="price"]').fill('2150');await buyer.locator('input[name="days"]').fill('8');await buyer.locator('input[name="place"]').fill('თბილისი');await button(buyer,'პირობების გაგზავნა').click();await buyer.getByRole('heading',{level:1,name:'პირობების დადასტურება',exact:true}).waitFor();await shots(buyer,'deal-terms');deal=await getDeal(ids.buyer,dealId);assert.equal(Number(deal.total_price),2150);assert.equal(deal.buyer_confirmed_at,null);assert.equal(deal.supplier_confirmed_at,null);
await go(supplier,`/deals/view/?id=${dealId}`,'პირობების დადასტურება');
// Hold the buyer's already-versioned request so background rereads cannot race this stale-revision test.
let captured,release;const capturedRequest=new Promise(r=>{captured=r;}),releaseRequest=new Promise(r=>{release=r;});
await buyer.route('**/rpc/confirm_deal_terms',async r=>{captured();await releaseRequest;await r.continue();});
await button(buyer,'პირობების დადასტურება').click();await capturedRequest;
await button(supplier,'პირობების დადასტურება').click();await supplier.getByText('მომწოდებელი: დადასტურდა',{exact:true}).waitFor();release();
await button(buyer,'განახლებულ პირობებს გავეცანი').waitFor();await buyer.unroute('**/rpc/confirm_deal_terms');assert.equal((await getDeal(ids.buyer,dealId)).buyer_confirmed_at,null);await button(buyer,'განახლებულ პირობებს გავეცანი').click();await button(buyer,'პირობების დადასტურება').click();await button(buyer,'შესრულების დაწყება').waitFor();report.checks.push('Both sides confirm; real MA904 reread and explicit review');
await button(buyer,'შესრულების დაწყება').click();await buyer.getByRole('heading',{level:1,name:'შესრულება',exact:true}).waitFor();await shots(buyer,'deal-progress');deal=await getDeal(ids.buyer,dealId);await rpc(ids.supplier,'advance_deal',{p_deal_id:dealId,p_stage:'complete',p_expected_revision:deal.revision},'MA906');await go(supplier,`/deals/view/?id=${dealId}`,'შესრულება');assert.equal(await button(supplier,'დიახ, დასრულებულია').count(),0);
await button(buyer,'დიახ, დასრულებულია').click();await button(buyer.locator('#deal-action'),'დასრულების დადასტურება').click();await buyer.getByRole('heading',{level:1,name:'გარიგება დასრულებულია',exact:true}).waitFor();await shots(buyer,'deal-complete');await buyer.getByRole('radio',{name:'5 ვარსკვლავი',exact:true}).check();await buyer.getByLabel('კომენტარი (არასავალდებულო)').fill('შეთანხმებული პირობები შესრულდა.');await button(buyer,'შეფასების გაგზავნა').click();await buyer.getByText('შეფასება: 5 / 5',{exact:true}).waitFor();await buyer.reload();await buyer.getByText('შეფასება: 5 / 5',{exact:true}).waitFor();deal=await getDeal(ids.buyer,dealId);assert.equal(deal.rating,5);await rpc(ids.buyer,'rate_deal',{p_deal_id:dealId,p_expected_revision:deal.revision,p_rating:4,p_review:'again'},'MA903');report.checks.push('Buyer-only completion and one-time persisted rating');
await go(outsider,`/deals/view/?id=${dealId}`,'გარიგებაზე წვდომა შეზღუდულია');assert.equal(await outsider.locator('main a[href^="tel:"]').count(),0);await go(guest,`/deals/view/?id=${dealId}`,'გარიგებაზე წვდომა შეზღუდულია');await go(admin,`/deals/view/?id=${dealId}`,'გარიგება დასრულებულია');assert.equal(await button(admin,'შეფასების გაგზავნა').count(),0);assert.equal((await rpc(ids.admin,'get_deal_contact',{p_deal_id:dealId})).length,2);
let failRead=true;await supplier.route('**/rpc/get_deal',r=>{if(failRead){return r.fulfill({status:503,json:{message:'Local QA read unavailable'}});}return r.continue();});await go(supplier,`/deals/view/?id=${dealId}`,'გარიგება ვერ ჩაიტვირთა');failRead=false;await button(supplier,'ხელახლა ცდა').click();await supplier.getByRole('heading',{level:1,name:'გარიგება დასრულებულია',exact:true}).waitFor();await supplier.unroute('**/rpc/get_deal');report.checks.push('Injected get_deal network error recovers through explicit retry');
await go(supplier,'/account/?tab=notifications&alerts=all','შეტყობინებები');await supplier.locator(`main a[href="/deals/view/?id=${dealId}"]`).filter({hasText:'გარიგება შეფასდა'}).waitFor();report.checks.push('Guest/outsider deny; admin read-only; metadata notification URL and label');
const cancelOffer=await rpc(ids.supplier,'send_offer',{...offerArgs,p_request_id:requests[1]}),cancelled=await rpc(ids.buyer,'select_offer_deal',{p_offer_id:cancelOffer.id,p_expected_updated_at:cancelOffer.updated_at});await go(buyer,`/deals/view/?id=${cancelled.id}`,'მომწოდებელი არჩეულია');await button(buyer,'გარიგების გაუქმება').click();await button(buyer.locator('#deal-action'),'გარიგების გაუქმება').click();await buyer.getByRole('heading',{level:1,name:'გარიგება გაუქმებულია',exact:true}).waitFor();assert.equal(await buyer.locator('main a[href^="tel:"]').count(),0);await rpc(ids.buyer,'get_deal_contact',{p_deal_id:cancelled.id},'MA901');await shots(buyer,'deal-cancelled');report.checks.push('Cancellation revokes contact');assert.deepEqual(report.pageErrors,[]);report.unexpectedConsoleErrors=report.consoleErrors.filter(m=>!/^Failed to load resource: the server responded with a status of (400|403|404|409|503)/.test(m)&&!/MarketStore:.*Local QA read unavailable/.test(m));assert.deepEqual(report.unexpectedConsoleErrors,[]);report.pass=true;
}catch(error){report.pass=false;report.error=error.stack;for(let i=0;i<pages.length;i++){await pages[i].screenshot({path:`${output}/failure-${i}.png`,fullPage:true});}console.error(error.message);process.exitCode=1;}
finally{await browser?.close();await new Promise(resolve=>server.close(resolve));try{await sql.query('begin');await sql.query('delete from meetany_private.notifications where request_id=any($1::uuid[])',[requests]);await sql.query('delete from meetany_private.deal_events where deal_id in (select id from meetany_private.deals where request_id=any($1::uuid[]))',[requests]);await sql.query('delete from meetany_private.deals where request_id=any($1::uuid[])',[requests]);await sql.query('delete from public.requests where id=any($1::uuid[])',[requests]);await sql.query('delete from neon_auth."user" where id=any($1::uuid[])',[Object.values(ids)]);await sql.query('commit');report.cleanup=true;}catch(error){await sql.query('rollback');report.cleanupError=error.message;report.fixtureIds={ids,requests};process.exitCode=1;}await sql.end();fs.writeFileSync(`${output}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify({pass:report.pass,checks:report.checks.length,views:report.views.length,cleanup:report.cleanup}));}
