import {chromium} from 'playwright';
import {auth,credentials,token,safe} from './e2e/lib.mjs';
import {guard} from './visual/lib/browser.mjs';
import assert from 'node:assert/strict';
const origin='http://localhost:3004';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),state={blocked:[],chat:null,interceptions:0},errors=[];
page.on('pageerror',e=>errors.push(e.message));await guard(context,state);
await context.route('**/api/analytics/registration**',r=>r.fulfill({json:{enabled:false},status:202}));
let profilePayload,productsPayload,distributionPayload;
try{
const login=await page.request.post(auth+'/sign-in/email',{data:credentials('linen')});assert(login.ok(),'demo login '+login.status());
const jwt=await token(page),rawResponse=await page.request.post(origin+'/api/db/rpc/my_profile',{headers:{Authorization:'Bearer '+jwt},data:{}}),rawData=await rawResponse.json(),raw=Array.isArray(rawData)?rawData[0]:rawData;assert(raw?.id,'own profile found');
await context.route('**/api/db/rpc/update_my_profile',r=>{profilePayload=r.request().postDataJSON();return r.fulfill({json:{...raw,name:profilePayload.p_name,company:profilePayload.p_company,city:profilePayload.p_city,offers:profilePayload.p_offers,seeks:profilePayload.p_seeks,lat:profilePayload.p_lat,lng:profilePayload.p_lng}});});
await context.route('**/api/db/rpc/set_my_products',r=>{productsPayload=r.request().postDataJSON();return r.fulfill({json:productsPayload.p_items});});
await context.route('**/api/db/rpc/set_my_distribution',r=>{distributionPayload=r.request().postDataJSON();return r.fulfill({json:{}});});
await page.goto(origin+'/account/?tab=profile');await page.locator('#offers').waitFor({timeout:60000});await page.waitForFunction(()=>document.querySelector('.profile-location-map .companies-map__canvas')?.getAttribute('aria-busy')==='false',null,{timeout:45000});
const offerGroup=page.locator('.profile-items').filter({has:page.locator('#offers')});if(await offerGroup.locator('li').count()>=8)await offerGroup.locator('li button').first().click();
await page.locator('#offers').fill('QA მიწოდება');await page.locator('#offers').press('Enter');assert(await offerGroup.getByText('QA მიწოდება',{exact:true}).count());
await page.locator('.profile-city-choices').getByRole('radio',{name:'ბათუმი',exact:true}).check();
await page.locator('.profile-location-map').click({position:{x:120,y:140}});const marker=page.locator('.profile-location-map .map-pin');await marker.waitFor();await marker.focus();await page.keyboard.press('ArrowRight');
await page.getByRole('button',{name:'შენახვა',exact:true}).click();await page.locator('.account-save-feedback').getByText('ცვლილებები შენახულია.').waitFor({timeout:45000});assert(profilePayload.p_offers.includes('QA მიწოდება'));assert.equal(profilePayload.p_city,'batumi');assert(Number.isFinite(profilePayload.p_lat)&&Number.isFinite(profilePayload.p_lng));
await page.locator('#about').fill('QA ჩანაწერის ცვლილება');assert.equal(await page.locator('.account-save-feedback').count(),0);
for(const width of [1440,768,390,320]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(150);assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=width);assert(await page.locator('.profile-location-map').evaluate(el=>el.getBoundingClientRect().height)<=321);if(width===390)await page.locator('.account-main').screenshot({path:'/tmp/meetany-profile-editor-mobile.png'});}
console.log('PASS profile chips/city/map-click/keyboard/payload/save feedback, four widths');
await page.goto(origin+'/account/?tab=profile&section=products');await page.getByRole('button',{name:'პროდუქტების შენახვა',exact:true}).waitFor({timeout:45000});await page.getByRole('button',{name:'პროდუქტების შენახვა',exact:true}).click();await page.locator('.account-save-feedback').getByText('პროდუქტები შენახულია.').waitFor({timeout:45000});assert(Array.isArray(productsPayload.p_items));await page.locator('input[maxlength="80"]').first().fill('QA პროდუქტი');assert.equal(await page.locator('.account-save-feedback').count(),0);console.log('PASS product save feedback clears on edits');
const settingsResponse=await page.request.post(origin+'/api/db/rpc/my_business_settings',{headers:{Authorization:'Bearer '+jwt},data:{}}),settings=await settingsResponse.json();
await context.route('**/api/db/rpc/my_business_settings',r=>r.fulfill({json:{...settings,distributor:true,distribution:{regions:['tbilisi'],categories:[],channels:['horeca'],brands:[],warehouse:'none',transport:'none',coldChain:false,minOrder:'',exclusive:false}}}));
await page.goto(origin+'/account/?tab=profile&section=distribution');await page.getByRole('button',{name:'პროფილის შენახვა',exact:true}).waitFor({timeout:45000});await page.getByLabel('ბრენდები',{exact:false}).fill('Alpha, Beta');await page.getByRole('button',{name:'პროფილის შენახვა',exact:true}).click();await page.locator('.account-save-feedback').getByText('დისტრიბუციის პროფილი შენახულია.').waitFor({timeout:45000});assert.deepEqual(distributionPayload.p_brands,['Alpha','Beta']);await page.getByLabel('ბრენდები',{exact:false}).fill('Gamma');assert.equal(await page.locator('.account-save-feedback').count(),0);console.log('PASS distribution save payload/feedback clears on edits');
await page.goto(origin+'/account/?tab=business');await page.locator('.business-plan').first().waitFor({timeout:45000});for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth)<=width);}await page.locator('.business-panel--plans').screenshot({path:'/tmp/meetany-business-plans-mobile.png'});assert(await page.getByRole('button',{name:'მიმდინარე პაკეტი',exact:true}).isDisabled());console.log('PASS package compact layout/current plan explicit');
await page.goto(origin+'/account/?tab=notifications&alerts=all');await page.locator('details').getByText('შეტყობინებების პარამეტრები',{exact:true}).waitFor({timeout:45000});assert.equal(await page.locator('details').filter({has:page.getByText('შეტყობინებების პარამეტრები',{exact:true})}).getAttribute('open'),null);await page.getByText('შეტყობინებების პარამეტრები',{exact:true}).click();assert(await page.getByRole('form',{name:'ახალი მოთხოვნების შეტყობინებები'}).isVisible());console.log('PASS notifications preferences disclosure');
assert.deepEqual(errors,[]);assert.deepEqual(state.blocked,[]);console.log('PASS zero runtime errors / blocked writes; all saves mocked');
}catch(e){console.error(safe(e.stack));process.exitCode=1;}finally{await browser.close();}
