// BASE=http://localhost:3003 node qa/site-walk-b.mjs
// Read-only UI checks. Only error responses and pagination size are intercepted.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { adminSession } from './admin-session.mjs';
process.env.QA_ORIGIN=process.env.BASE||'http://localhost:3003';
const {rpc,origin}=await import('./e2e/lib.mjs');
const dir='qa/shots/final-2026-09-29/admin';fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const report={checks:[],errors:[]};
const save=()=>fs.writeFileSync(`${dir}/walk.json`,JSON.stringify(report,null,2));
async function check(name,fn){try{const evidence=await fn();report.checks.push({name,pass:true,evidence});console.log('PASS '+name);}catch(e){report.checks.push({name,pass:false,error:e.message.slice(0,350)});console.log('FAIL '+name);}save();}
async function shot(p,name){await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:`${dir}/${name}.png`,fullPage:true});await p.screenshot({path:`${dir}/${name}-viewport.png`});assert.equal(await p.evaluate(()=>Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)-innerWidth),0,'overflow');}
async function ready(p){await p.waitForTimeout(350);await p.locator('main .ma-stat').first().waitFor({timeout:60000});await p.waitForFunction(()=>!document.querySelector('main [aria-busy="true"]')&&!document.querySelector('main')?.innerText.includes('იტვირთება…'));}
async function nav(p,path){await p.goto(origin+path,{waitUntil:'networkidle'});await ready(p);}
async function choose(p,id,name){await p.locator('#'+id).click();await p.getByRole('option',{name,exact:true}).click();await ready(p);}
try{
 const {page:p}=await adminSession(browser,'owner_admin');p.setDefaultTimeout(20000);
 p.on('pageerror',e=>report.errors.push(e.message.slice(0,200)));
 p.on('console',m=>{if(m.type()==='error'&&!p.qaInjected)report.errors.push(m.text().slice(0,200));});
 for(const width of [1440,390]){
  await p.setViewportSize({width,height:width===390?844:1000});
  await check(`KPI ${width}`,async()=>{await nav(p,'/admin/');const stats=await rpc(p,'admin_stats');assert.deepEqual((await p.locator('main .ma-stat__value').allTextContents()).map(Number),['users','companies','verified','open','offers','chosen'].map(k=>stats[k]));});
  for(const tab of ['requests','users','offers']){
   await check(`${tab} empty/search ${width}`,async()=>{await nav(p,`/admin/?tab=${tab}&q=zzzz-no-match`);assert.equal(await p.locator('main tbody tr').count(),0);await p.getByText('ამ ფილტრებით ჩანაწერები ვერ მოიძებნა',{exact:true}).waitFor();await shot(p,`${tab}-empty-${width}`);await p.getByRole('button',{name:'ფილტრების გასუფთავება',exact:true}).first().click();await ready(p);assert(await p.locator('main tbody tr').count()>0);await p.locator('#admin-search').fill('zzzz-no-match');await p.waitForURL(/q=zzzz-no-match/);await ready(p);assert.equal(await p.locator('main tbody tr').count(),0);});
   await check(`${tab} status/dropdown ${width}`,async()=>{await nav(p,`/admin/?tab=${tab}`);await choose(p,'admin-status',tab==='requests'?'ღია':tab==='users'?'დადასტურებული კომპანია':'გაგზავნილი');assert(new URL(p.url()).searchParams.has('status'));await shot(p,`${tab}-filtered-${width}`);await p.locator('#admin-status').focus();await p.keyboard.press('Space');assert.equal(await p.locator('#admin-status').getAttribute('aria-expanded'),'true');await p.keyboard.press('Escape');assert.equal(await p.locator('#admin-status').getAttribute('aria-expanded'),'false');assert(await p.locator('#admin-status').evaluate(el=>el===document.activeElement));if(tab==='users'){await choose(p,'admin-role','კომპანია');assert.equal(new URL(p.url()).searchParams.get('role'),'company');}});
  }
  for(const tab of ['requests','users','offers','audit','contacts']){
   await check(`${tab} error/retry ${width}`,async()=>{const method={requests:'admin_search_requests',users:'admin_search_users',offers:'admin_search_offers',audit:'admin_list_audit_v2',contacts:'admin_contact_events'}[tab];p.qaInjected=true;try{await p.route(`**/rpc/${method}`,r=>r.abort());await nav(p,`/admin/?tab=${tab}`);await p.getByText(tab==='contacts'?'კონტაქტები ვერ ჩაიტვირთა':'ჩანაწერები ვერ ჩაიტვირთა',{exact:true}).waitFor();await shot(p,`${tab}-error-${width}`);await p.unroute(`**/rpc/${method}`);await p.getByRole('button',{name:'ხელახლა ცდა',exact:true}).click();await ready(p);assert.equal(await p.locator('main [role="alert"]').count(),0);}finally{await p.unroute(`**/rpc/${method}`);p.qaInjected=false;}});
  }
  await check(`contacts period ${width}`,async()=>{await nav(p,'/admin/?tab=contacts');for(const label of ['დღეს','7 დღე','30 დღე']){await choose(p,'contact-period',label);await shot(p,`contacts-${label==='დღეს'?'day':label==='7 დღე'?'week':'month'}-${width}`);}await choose(p,'contact-kind','დარეკვა');await choose(p,'contact-target','მოთხოვნა');await shot(p,`contacts-filtered-${width}`);});
  await check(`pagination ${width}`,async()=>{await p.route('**/rpc/admin_search_requests',async route=>{const body=route.request().postDataJSON();await route.continue({postData:JSON.stringify({...body,p_limit:1})});});await nav(p,'/admin/?tab=requests');const first=await p.locator('main tbody tr').first().innerText();await p.getByRole('button',{name:'შემდეგი გვერდი',exact:true}).click();await ready(p);assert(new URL(p.url()).searchParams.has('cursor'));assert.notEqual(await p.locator('main tbody tr').first().innerText(),first);await shot(p,`pagination-${width}`);await p.getByRole('button',{name:'პირველი გვერდი',exact:true}).click();await ready(p);assert.equal(await p.locator('main tbody tr').first().innerText(),first);await p.unroute('**/rpc/admin_search_requests');});
  await check(`moderation validation/focus ${width}`,async()=>{await nav(p,'/admin/?tab=requests');const opener=p.locator('main tbody tr').first().getByRole('button',{name:'დამალვა',exact:true});await opener.click();const d=p.locator('dialog#moderation');await d.waitFor({state:'visible'});await d.locator('button[type="submit"]').click();const message=await d.locator('textarea').evaluate(el=>el.validationMessage);report.checks.push({name:`reason message ${width}`,pass:/[ა-ჰ]/.test(message),evidence:message});await d.locator('textarea').fill('ა');await d.locator('button[type="submit"]').click();const short=await d.locator('textarea').evaluate(el=>el.validationMessage);report.checks.push({name:`short reason ${width}`,pass:/[ა-ჰ]/.test(short),evidence:short});await shot(p,`moderation-validation-${width}`);await p.keyboard.press('Escape');await d.waitFor({state:'hidden'});assert(await opener.evaluate(el=>el===document.activeElement));});
  await check(`company cancel ${width}`,async()=>{await nav(p,'/admin/?tab=users&role=company&status=active');const row=p.locator('main tbody tr').first();for(const name of [/^დადასტურება$|^დადასტურების მოხსნა$/,/^დაბლოკვა$/]){await row.getByRole('button',{name}).click();const d=p.locator('dialog#moderation');await d.waitFor({state:'visible'});await shot(p,`company-${String(name).includes('დაბლოკვა')?'block':'verify'}-${width}`);await d.getByRole('button',{name:'გაუქმება',exact:true}).click();await d.waitFor({state:'hidden'});}});
  await check(`navigation ${width}`,async()=>{const menu=p.getByRole('navigation',{name:'ადმინისტრირების განყოფილებები'});for(const tab of ['requests','users','offers','audit','contacts']){const a=menu.locator(`a[href="/admin/?tab=${tab}"]`);await a.click();await ready(p);assert.equal(await a.getAttribute('aria-current'),'page');}const back=p.getByRole('link',{name:'საიტზე დაბრუნება',exact:true});assert(await back.isVisible(),'site return is hidden');await back.click();await p.waitForURL(origin+'/');});
 }
 for(const key of ['guest','owner_user','owner_company','admin']){
  const session=key==='guest'?{page:await browser.newPage()}:await adminSession(browser,key);const q=session.page;
  for(const width of [1440,390]){await q.setViewportSize({width,height:width===390?844:1000});for(const tab of ['requests','users','offers','audit','contacts'])await check(`denial ${key} ${tab} ${width}`,async()=>{await q.goto(`${origin}/admin/?tab=${tab}`,{waitUntil:'networkidle'});await q.getByText('ეს გვერდი ხელმისაწვდომია მხოლოდ ადმინისტრატორისთვის.',{exact:true}).waitFor({timeout:60000});assert.equal(await q.locator('main table').count(),0);if(key==='guest')assert.equal(await q.getByRole('link',{name:'შესვლა',exact:true}).last().getAttribute('href'),'/account/?next=%2Fadmin%2F');await shot(q,`denial-${key}-${tab}-${width}`);});}
 }
 const q=await browser.newPage();for(const width of [1440,390]){await q.setViewportSize({width,height:width===390?844:1000});for(const [name,url,text] of [['terms','/terms/','წესები და კონფიდენციალურობა'],['404','/missing-walk-b/','გვერდი ვერ მოიძებნა'],['request-missing','/requests/view/?id=00000000-0000-4000-8000-000000000001','მოთხოვნა'],['company-missing','/companies/view/?id=00000000-0000-4000-8000-000000000001','კომპანია']])await check(`${name} ${width}`,async()=>{const response=await q.goto(origin+url,{waitUntil:'networkidle'});await q.locator('main').waitFor();await q.waitForFunction(()=>!document.querySelector('main [aria-busy="true"]'));assert((await q.locator('main').innerText()).includes(text));await shot(q,`${name}-${width}`);return {http:response.status(),text:(await q.locator('main').innerText()).slice(0,300)};});}
 await check('terms links',async()=>{await q.goto(origin+'/terms/');const links=[...new Set(await q.locator('a[href]').evaluateAll(as=>as.map(a=>a.getAttribute('href'))))];const results=[];for(const href of links){if(href.startsWith('#')){assert(await q.locator(href).count());continue;}if(!href.startsWith('/'))continue;const r=await q.request.get(origin+href);assert(r.status()<400,href);results.push({href,status:r.status()});}return results;});
 await check('security/robots/sitemap',async()=>{const r=await q.request.head(origin+'/admin/');const headers=r.headers();for(const h of ['content-security-policy','x-content-type-options','x-frame-options','referrer-policy','permissions-policy'])assert(headers[h]);assert(!headers['content-security-policy'].includes('unsafe-eval'));for(const path of ['/robots.txt','/sitemap.xml'])assert((await q.request.get(origin+path)).ok());return headers;});
}catch(e){report.fatal=e.message.slice(0,350);}finally{save();await browser.close();}
console.log(JSON.stringify({passed:report.checks.filter(x=>x.pass).length,total:report.checks.length,errors:report.errors,fatal:report.fatal}));

process.exitCode = report.fatal || report.checks.some(x => !x.pass) || report.errors.length ? 1 : 0;
