const {chromium}=require('../../.qa/node_modules/playwright-core');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const exe=require('node:os').homedir()+'/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
const pages=['t21-requests','t22-offers','t23-new-request','t24-account','t24-admin','t25-companies','t25-company'];
const variants=[['t25-company','?id=nushi','new'],['t25-company','?id=forma','incomplete'],['t24-account','?role=client','client'],['t24-account','?role=client&tab=profile','client-profile'],['t24-account','?role=company&tab=profile','company-profile'],['t24-admin','?tab=users','users'],['t22-offers','?state=chosen','chosen']];
fs.mkdirSync(path.join(__dirname,'shots/r2'),{recursive:true});
(async()=>{const browser=await chromium.launch({executablePath:exe});const page=await browser.newPage();const report=[];const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
for(const [file,query,label] of [...pages.map(f=>[f,'','']),...variants])for(const width of [1280,768,390,320]){
 await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:4032/prototypes/'+file+'.html'+query);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>i.hasAttribute('src')).map(i=>i.decode().catch(()=>{})));document.getAnimations().forEach(a=>{if(a.effect.getTiming().iterations!==Infinity)a.finish()})});
 const result=await page.evaluate(()=>{const visible=e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden'&&!e.closest('[hidden]');const dialog=document.querySelector('dialog[open]');const root=dialog||document;return{overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,broken:[...document.images].filter(e=>visible(e)&&e.hasAttribute('src')&&!e.naturalWidth).map(e=>e.src),small:[...root.querySelectorAll('a,button,input,select,textarea,summary')].filter(visible).filter(e=>!e.classList.contains('ma-skip')).map(e=>{const target=e.matches('input[type=checkbox],input[type=radio]')?e.closest('label'):e;const r=target.getBoundingClientRect();return{text:e.textContent.trim().slice(0,55)||e.id||e.getAttribute('aria-label'),w:r.width,h:r.height}}).filter(r=>r.w<43.9||r.h<43.9),clipped:[...root.querySelectorAll('h1,h2,h3,p,a,button,label')].filter(visible).filter(e=>e.scrollWidth>e.clientWidth+2&&getComputedStyle(e).overflowX==='hidden'&&!(e.matches('label[for=sort]')&&e.clientWidth===1&&getComputedStyle(e).clipPath==='inset(50%)')).map(e=>e.textContent.slice(0,70)),footer:dialog?.querySelector('.ma-sheet__footer')?.getBoundingClientRect().bottom||null}});
 report.push({page:file,variant:label,width,...result});
 if(width!==768)await page.screenshot({path:path.join(__dirname,'shots/r2',file+(label?'-'+label:'')+'-'+width+'.png'),fullPage:file!=='t23-new-request'});
}
fs.writeFileSync(path.join(__dirname,'qa-report.json'),JSON.stringify({report,errors},null,2));console.log(JSON.stringify({errors,issues:report.filter(r=>r.overflow||r.broken.length||r.clipped.length||r.small.length)},null,2));
assert.equal(errors.length,0,'No JavaScript errors');assert.equal(report.filter(r=>r.overflow||r.broken.length||r.clipped.length||r.small.length).length,0,'Viewport accessibility checks');
await page.setViewportSize({width:320,height:600});await page.goto('http://127.0.0.1:4032/prototypes/t23-new-request.html');await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>i.hasAttribute('src')).map(i=>i.decode().catch(()=>{})));document.getAnimations().forEach(a=>{if(a.effect.getTiming().iterations!==Infinity)a.finish()})});
assert(await page.locator('#photo-preview').isHidden());await page.locator('#photo').setInputFiles(path.resolve(__dirname,'../dist/assets/photos/cardboard-packaging.jpg'));await page.waitForFunction(()=>!document.querySelector('#photo-preview').hidden);assert.equal(await page.locator('#photo-preview img').getAttribute('alt'),'');await page.locator('#photo-remove').click();assert(await page.locator('#photo-preview').isHidden());
await page.locator('#photo').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('invalid image')});await page.waitForFunction(()=>!document.querySelector('#photo-error').hidden);assert(await page.locator('#photo-preview').isHidden());
assert(await page.locator('button[form=new-request-form]').isVisible());const rect=await page.locator('.ma-sheet__footer').last().boundingBox();assert(rect.y+rect.height<=601);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'new-request-open');
await page.goto('http://127.0.0.1:4032/prototypes/t21-requests.html');assert.equal(await page.locator('.ma-rcard').count(),4);await page.getByRole('button',{name:/^ფილტრი/ }).click();await page.locator('#filters [data-category=furniture]').click();assert.equal(await page.locator('#filter-apply').innerText(),'2 მოთხოვნის ჩვენება');await page.locator('#filter-apply').click();assert.equal(await page.locator('.ma-rcard').count(),2);await page.locator('#query').fill('<script>');assert.equal(await page.locator('.ma-rcard').count(),0);assert(await page.locator('.ma-empty').isVisible());
await page.goto('http://127.0.0.1:4032/prototypes/t25-companies.html');await page.getByRole('button',{name:/^ფილტრი/}).click();await page.locator('#filters [data-industry=furniture]').click();await page.locator('#filters [data-verified]').check();assert.equal(await page.locator('#company-apply').innerText(),'1 კომპანიის ჩვენება');await page.locator('#company-apply').click();assert.equal(await page.locator('.r2-company-row').count(),1);await page.getByRole('link',{name:'პროფილი',exact:false}).filter({hasText:'პროფილი'}).first().click();assert(await page.locator('h1').filter({hasText:'კერა'}).isVisible());
console.log('PASS: photo select/remove/broken, 320×600 footer, Esc focus return, filter counts, empty search');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
