const {chromium}=require('../../.qa/node_modules/playwright-core');const fs=require('node:fs'),path=require('node:path');
const exe=require('node:os').homedir()+'/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
(async()=>{const b=await chromium.launch({executablePath:exe}),p=await b.newPage({viewport:{width:1280,height:900}});await p.goto('http://127.0.0.1:4032/prototypes/t21-requests.html');await p.evaluate(()=>document.fonts.ready);
const contrast=await p.evaluate(()=>{const cx=document.createElement('canvas').getContext('2d');function rgb(v){cx.fillStyle=v;cx.fillRect(0,0,1,1);return [...cx.getImageData(0,0,1,1).data].slice(0,3)}function luminance(v){const c=rgb(v).map(x=>{x/=255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4});return .2126*c[0]+.7152*c[1]+.0722*c[2]}const s=getComputedStyle(document.documentElement),out=[];for(const [fg,bg]of [['--text','--white'],['--text-2','--white'],['--text-3','--white'],['--text-3','--bg-subtle'],['--white','--action'],['--white','--blue-800'],['--white','--blue-900'],['--blue-700','--blue-50'],['--success-700','--success-50'],['--warning-700','--warning-50']]){const a=luminance(s.getPropertyValue(fg)),b=luminance(s.getPropertyValue(bg));out.push({fg,bg,ratio:Math.round((Math.max(a,b)+.05)/(Math.min(a,b)+.05)*100)/100})}return out});
const sprite=fs.readFileSync(path.resolve(__dirname,'../dist/icons.svg'),'utf8');const missing=[],assets=[],screens=[];
for(const file of ['t21-requests','t22-offers','t23-new-request','t24-account','t24-admin','t25-companies','t25-company'])for(const width of [1280,768,390,320]){
 await p.setViewportSize({width,height:900});await p.goto('http://127.0.0.1:4032/prototypes/'+file+'.html');await p.evaluate(()=>document.fonts.ready);
 for(const id of await p.locator('use').evaluateAll(es=>es.map(e=>e.getAttribute('href').split('#')[1])))if(!sprite.includes('id="'+id+'"'))missing.push({file,width,id});
 const urls=await p.evaluate(()=>[...new Set([...document.querySelectorAll('img[src],link[rel=stylesheet],script[src]')].map(e=>e.src||e.href).concat([...document.querySelectorAll('*')].flatMap(e=>[getComputedStyle(e).backgroundImage,getComputedStyle(e,'::before').backgroundImage]).flatMap(v=>[...v.matchAll(/url\(["']?([^"')]+)["']?\)/g)].map(m=>new URL(m[1],location.href).href))))]);
 for(const url of urls){const response=await p.request.get(url);if(!response.ok())assets.push({file,width,url,status:response.status()})}
 screens.push({file,width,assets:urls.length,contrastPairs:contrast.length});
}
const extra=[];
for(const [file,q]of [['t21-requests','state=mine'],['t21-requests','state=closed'],['t21-requests','state=loading'],['t21-requests','state=empty'],['t22-offers','state=closed'],['t22-offers','state=empty'],['t24-account','state=empty'],['t24-admin','state=empty']]){await p.setViewportSize({width:320,height:900});await p.goto('http://127.0.0.1:4032/prototypes/'+file+'.html?'+q);await p.evaluate(()=>document.getAnimations().forEach(a=>{if(a.effect.getTiming().iterations!==Infinity)a.finish()}));extra.push({file,q,overflow:await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)})}
await p.goto('http://127.0.0.1:4032/prototypes/t23-new-request.html');await p.evaluate(()=>document.fonts.ready);await p.locator('#photo').setInputFiles(path.resolve(__dirname,'../dist/assets/photos/cardboard-packaging.jpg'));await p.waitForFunction(()=>!document.querySelector('#photo-preview').hidden);await p.locator('#photo-remove').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(__dirname,'shots/r2/t23-photo-320.png')});
await p.setViewportSize({width:320,height:500});await p.locator('#body').focus();await p.screenshot({path:path.join(__dirname,'shots/r2/t23-keyboard-height-320.png')});
await p.goto('http://127.0.0.1:4032/prototypes/t21-requests.html');await p.getByRole('button',{name:/^ფილტრი/}).click();await p.screenshot({path:path.join(__dirname,'shots/r2/t21-filters-320.png')});
fs.writeFileSync(path.join(__dirname,'extra-checks.json'),JSON.stringify({contrast,missing,assets,screens,extra,keyboard:'320×500 visual viewport simulation; not a physical mobile keyboard'},null,2));
console.log(JSON.stringify({contrast,missing,assets,screens,extra},null,2));
if(assets.length||missing.length||extra.some(r=>r.overflow)||contrast.some(r=>r.ratio<4.5))process.exitCode=1;await b.close()})();
