const {chromium}=require('../../.qa/node_modules/playwright-core');
const assert=require('node:assert/strict'),path=require('node:path');
const executablePath=require('node:os').homedir()+'/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing';
(async()=>{const browser=await chromium.launch({executablePath}),page=await browser.newPage({viewport:{width:320,height:900}}),base='http://127.0.0.1:4032/prototypes/';
try{
 await page.goto(base+'t21-requests.html');await page.locator('[data-open=filters]').click();assert(await page.locator('#filters [data-category=textiles]').isHidden());await page.locator('#filters [data-category=furniture]').click();await page.locator('#filter-apply').click();assert.equal(await page.locator('[data-filter-count]').textContent(),'2');await page.screenshot({path:path.join(__dirname,'shots/r2/t21-two-filters-320.png'),fullPage:true});await page.locator('[data-open=filters]').click();await page.screenshot({path:path.join(__dirname,'shots/r2/t21-sheet-two-filters-320.png')});await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.dataset.open),'filters');await page.locator('#active-filters [data-clear]').click();assert.equal(await page.locator('.ma-rcard').count(),6);
 await page.goto(base+'t25-companies.html');await page.locator('[data-open=filters]').click();await page.locator('#filters .r2-more summary').click();await page.locator('#filters [data-industry=textiles]').click();await page.locator('#company-apply').click();assert(await page.locator('.ma-empty').isVisible());await page.locator('#company-active [data-company-clear]').click();assert.equal(await page.locator('.r2-company-row').count(),4);
 await page.goto(base+'t25-company.html?id=pack');await page.locator('.r2-sticky a').click();assert.equal(await page.locator('#category').inputValue(),'შეფუთვა და წარმოება');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'new-request-open');
 console.log('PASS: hidden zero facets, two filters, sheet/Esc focus, clear, catalogue empty/reset, profile CTA category');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
