"use client";
import { useCallback, useEffect, useState } from 'react';
import type { Store } from '../../lib/market-client';
import { useBusinessResource, businessError } from '../../lib/business-client';
import { useRouter } from 'next/navigation';
import { Sheet } from '../ui/Sheet';
import {useUnsavedDraft} from '../../lib/use-unsaved-draft';
import { Button } from '../ui/Button';
import { toast } from '../Toasts';
import styles from './admin-edit.module.css';
import {siteContentDefaults} from '../../lib/site-content-defaults';
type Content=Record<string,string>;
const texts=[['heroTitle','მთავარი სათაური'],['heroAccent','სათაურის გამორჩეული ნაწილი'],['heroSubtitle','მთავარი აღწერა'],['companiesTitle','კომპანიების ბლოკის სათაური'],['requestsTitle','მოთხოვნების ბლოკის სათაური'],['businessTitle','კატალოგის სათაური'],['businessSubtitle','კატალოგის აღწერა']];
export function AdminContentEditor({store}:{store:Store}){
 const read=store.siteContent;const load=useCallback(()=>read(),[read]);const resource=useBusinessResource<Content>(load,'site-editor');
 return resource.error?<div role="alert">{businessError(resource.error)}<Button onClick={resource.reload}>თავიდან ცდა</Button></div>:resource.data?<ContentForm store={store} initial={resource.data}/>:<p role="status">გვერდის შიგთავსი იტვირთება…</p>;
}
function ContentForm({store,initial}:{store:Store;initial:Content}){
 const [saved,setSaved]=useState({...siteContentDefaults,...initial});
 const [draft,setDraft]=useState({...siteContentDefaults,...initial}),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(''),[error,setError]=useState(''),[preview,setPreview]=useState(false);
 const router=useRouter();const [leaving,setLeaving]=useState<string|null>(null);const dirty=JSON.stringify(draft)!==JSON.stringify(saved);useUnsavedDraft(dirty);
 useEffect(()=>{if(!dirty)return;const protect=(event:MouseEvent)=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const link=(event.target as Element)?.closest('a[href]');if(!(link instanceof HTMLAnchorElement)||!['http:','https:'].includes(link.protocol)||link.target==='_blank'||link.hasAttribute('download')||link.href===location.href)return;event.preventDefault();event.stopPropagation();setLeaving(link.href);};document.addEventListener('click',protect,true);return()=>document.removeEventListener('click',protect,true);},[dirty]);
 const change=(key:string,value:string)=>setDraft(v=>({...v,[key]:value}));
 async function upload(key:string,file:File|undefined){if(!file)return;setUploading(key);setError('');try{const result=await store.adminUploadPhoto(store.currentUser().id,file,'site');change(key,result.url);}catch(e){setError(businessError(e));}finally{setUploading('');}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await store.adminSaveSiteContent(draft);setSaved(draft);toast('საიტის შიგთავსი განახლებულია.');}catch(e){setError(businessError(e));}finally{setBusy(false);}}
 const photo=(key:string,label:string)=><div className={styles.imageField} key={key}><strong>{label}</strong>{draft[key]?<div className={styles.photo}><img src={draft[key]} alt={label}/><Button variant="ghost" type="button" onClick={()=>change(key,'')} disabled={busy||!!uploading}>საწყის ფოტოზე დაბრუნება</Button></div>:null}<label className={styles.upload}><span>{uploading===key?'იტვირთება…':'ფოტოს არჩევა'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy||!!uploading} onChange={e=>void upload(key,e.target.files?.[0])}/></label></div>;
 return <><form onSubmit={save} className={styles.cms}><section className={styles.surface}><h2>ტექსტები</h2><div className={styles.grid}>{texts.map(([key,label])=><label className={styles.field} key={key}><span>{label}</span><textarea aria-label={label} className="ma-textarea" rows={key.endsWith('Subtitle')?3:2} maxLength={1000} value={draft[key]||''} onChange={e=>change(key,e.target.value)} disabled={busy}/></label>)}</div></section><section className={styles.surface}><h2>მთავარი გვერდის ბარათები</h2><div className={styles.grid}>{[1,2,3,4].map(i=><div className={styles.imageField} key={i}>{photo(`heroImage${i}`,`ბარათის ფოტო ${i}`)}<label className={styles.field}><span>ბარათის წარწერა</span><input className="ma-input" maxLength={100} value={draft[`heroLabel${i}`]||''} onChange={e=>change(`heroLabel${i}`,e.target.value)}/></label></div>)}</div></section><details className={styles.surface}><summary>კომპანიების კატალოგის ფოტოები</summary><div className={styles.grid}>{[1,2,3,4,5,6,7,8,9].map(i=>photo(`businessImage${i}`,`კატალოგის ფოტო ${i}`))}</div></details>{preview?<section className={styles.preview} aria-label="შიგთავსის წინასწარი ნახვა"><h3>{draft.heroTitle||'მთავარი სათაური'} <span>{draft.heroAccent}</span></h3><p>{draft.heroSubtitle}</p><div className={styles.grid}>{[1,2,3,4].filter(i=>draft[`heroImage${i}`]).map(i=><figure key={i}><img src={draft[`heroImage${i}`]} alt={draft[`heroLabel${i}`]||''}/><figcaption>{draft[`heroLabel${i}`]}</figcaption></figure>)}</div></section>:null}{error?<p className="ma-field__error" role="alert">{error}</p>:null}<footer className={styles.actions}>{dirty?<span className={styles.dirty}>შეუნახავი ცვლილებები</span>:null}<Button variant="primary" type="submit" disabled={busy||!!uploading}>{busy?'ინახება…':'ცვლილებების გამოქვეყნება'}</Button><Button variant="secondary" type="button" onClick={()=>setPreview(v=>!v)}>{preview?'გადახედვის დახურვა':'წინასწარი ნახვა'}</Button></footer></form><Sheet open={!!leaving} title="შეუნახავი ცვლილებები" onClose={()=>setLeaving(null)} footer={<><Button type="button" variant="secondary" onClick={()=>setLeaving(null)}>რედაქტირების გაგრძელება</Button><Button type="button" variant="danger-quiet" onClick={()=>{const href=leaving;setLeaving(null);if(href){setDraft(saved);router.push(href);}}}>ცვლილებების გაუქმება</Button></>}><p>გვერდის დატოვებამდე შეინახე ცვლილებები.</p></Sheet></>;
}
