\set ON_ERROR_STOP 1
\o /dev/null
select t.as_super();
create table t.business_start as select count(*) n from t.passed;
grant select on t.business_start to public;
select t.signup('bx_client','bx-client@example.ge','{"role":"client","name":"Business Client","phone":"+995 522 771 001","city":"tbilisi"}');
select t.signup('bx_company','bx-company@example.ge','{"role":"company","name":"Business Owner","company":"Business Company","phone":"+995 522 771 002","city":"tbilisi","industry":"leasing"}');
select t.signup('bx_other','bx-other@example.ge','{"role":"client","name":"Other Client","phone":"+995 522 771 003","city":"tbilisi"}');
select t.signup('bx_admin','bx-admin@example.ge','{"role":"client","name":"Business Admin","phone":"+995 522 771 004","city":"tbilisi"}');
update public.profiles set role='admin' where id=t.uid('bx_admin');
select t.ok(meetany_private.is_category('leasing') and meetany_private.is_category('business_finance') and meetany_private.is_category('business_insurance'),'BX financial categories accepted');
select t.ok(not has_table_privilege('authenticated','meetany_private.company_plans','INSERT,UPDATE,DELETE'),'BX no self upgrade through table');
select t.ok(not has_table_privilege('authenticated','meetany_private.company_reviews','INSERT,UPDATE,DELETE'),'BX reviews RPC only');
select t.ok(not has_function_privilege('anonymous','public.save_company_review(uuid,integer,text)','EXECUTE'),'BX guest cannot write reviews');
select t.ok(not has_function_privilege('anonymous','public.my_business_settings()','EXECUTE'),'BX guest cannot read settings');
select t.as_user('bx_client');
select t.throws($q$select public.set_company_distributor(true)$q$,'MA201','BX client cannot become distributor');
select t.throws($q$select public.request_company_plan('vip')$q$,'MA201','BX client cannot request company plan');
select t.put('bx_request',(public.create_request('Business equipment needed','We need equipment with delivery','leasing','tbilisi')).id);
select t.throws($q$select public.save_company_review(t.get('bx_request'),5,'Very useful and professional service')$q$,'42501','BX no review before choice');
select t.as_user('bx_company');
select t.ok((public.set_company_distributor(true)->>'distributor')::boolean,'BX company can opt in to distributor');
select t.ok((public.my_business_settings()->>'distributor')::boolean,'BX distributor persists');
select t.ok(public.request_company_plan('vip')->'application'->>'status'='pending','BX request pending');
select t.ok(public.my_business_settings()->'membership'='null'::jsonb,'BX request never self activates');
select t.ok(public.cancel_company_plan_request()->'application'->>'status'='cancelled','BX company can cancel pending request');
select t.put('bx_plan',(public.request_company_plan('premium')->'application'->>'id')::uuid);
select t.throws($q$select public.admin_resolve_plan(t.get('bx_plan'),true,30,'')$q$,'MA003','BX company cannot activate own plan');
select t.put('bx_offer',(public.send_offer(t.get('bx_request'),'We can supply this equipment')).id);
select t.as_user('bx_client');
select public.choose_offer(t.get('bx_offer'));
select t.ok(jsonb_array_length(public.my_company_review_targets(t.uid('bx_company')))=1,'BX chosen request eligible');
select t.throws($q$select public.save_company_review(t.get('bx_request'),6,'Very useful and professional service')$q$,'22023','BX rating bounds');
select t.throws($q$select public.save_company_review(t.get('bx_request'),5,'short')$q$,'22023','BX minimum review length');
select t.put('bx_review',(public.save_company_review(t.get('bx_request'),5,'Very useful and professional service')->>'id')::uuid);
select t.ok(public.my_company_review_targets(t.uid('bx_company'))->0->>'status'='pending','BX author sees pending review');
select t.as_user('bx_other');
select t.ok(jsonb_array_length(public.my_company_review_targets(t.uid('bx_company')))=0,'BX another client has no eligibility');
select t.throws($q$select public.save_company_review(t.get('bx_request'),1,'A different client tries to replace this review')$q$,'42501','BX cannot overwrite peer review');
select t.throws($q$select public.admin_business_queue('plans')$q$,'MA003','BX queue admin only');
select t.throws($q$select public.admin_moderate_review(t.get('bx_review'),'published')$q$,'MA003','BX author cannot approve review');
select t.as_anon();
select t.ok((public.company_reviews(t.uid('bx_company'))->>'total')::int=0,'BX pending review not public');
select t.as_user('bx_admin');
select public.admin_moderate_review(t.get('bx_review'),'published');
select public.admin_resolve_plan(t.get('bx_plan'),true,30,'Conditions agreed');
select t.throws($q$select public.admin_resolve_plan(t.get('bx_plan'),true,30,'Again')$q$,'22023','BX cannot activate request twice');
select t.ok((public.admin_business_queue('plans')->>'total')::int>=1,'BX admin sees plans');
select t.throws($q$select public.admin_moderate_review(t.get('bx_review'),'hidden','')$q$,'22023','BX hiding requires reason');
select t.as_anon();
select t.ok((public.company_reviews(t.uid('bx_company'))->>'total')::int=1,'BX approved review public');
select t.ok((public.company_reviews(t.uid('bx_company'))->>'rating')::numeric=5,'BX correct average');
select t.ok(not(public.company_reviews(t.uid('bx_company'))->'items'->0 ? 'request_id'),'BX public review omits request id');
select t.ok(not(public.company_reviews(t.uid('bx_company'))->'items'->0 ? 'author_id'),'BX public review omits private author id');
select t.ok((select v->>'plan'='premium' and (v->>'distributor')::boolean from jsonb_array_elements(public.company_business_features()) v where v->>'id'=t.uid('bx_company')::text),'BX paid feature and independent distributor public');
select t.as_user('bx_client');
select public.save_company_review(t.get('bx_request'),4,'Edited review with additional helpful details');
select t.ok((public.company_reviews(t.uid('bx_company'))->>'total')::int=0,'BX edit returns to moderation');
select t.as_user('bx_admin');
select public.admin_moderate_review(t.get('bx_review'),'published');
select t.as_super();
update public.profiles set blocked=true where id=t.uid('bx_client');
select t.as_anon();
select t.ok((public.company_reviews(t.uid('bx_company'))->>'total')::int=0,'BX blocked reviewer excluded from ratings');
select t.as_user('bx_client');
select t.throws($q$select public.save_company_review(t.get('bx_request'),4,'Blocked author attempts another edit')$q$,'MA002','BX blocked user cannot write review');
select t.as_super();
update meetany_private.company_plans set expires_at=now()-interval '1 minute' where company_id=t.uid('bx_company');
select t.as_anon();
select t.ok((select v->'plan'='null'::jsonb from jsonb_array_elements(public.company_business_features()) v where v->>'id'=t.uid('bx_company')::text),'BX expired plan not publicly active');
select t.as_super();
update public.profiles set blocked=true where id=t.uid('bx_company');
select t.as_anon();
select t.ok(not exists(select 1 from jsonb_array_elements(public.company_business_features()) v where v->>'id'=t.uid('bx_company')::text),'BX blocked company excluded');
select t.throws($q$select public.company_reviews(t.uid('bx_company'))$q$,'MA302','BX blocked company review access denied');
select t.as_super();
select t.ok((select count(*)>=3 from meetany_private.business_audit),'BX moderation and activation audited');
-- Replacing a selected offer after admin intervention must not rate the previous supplier.
update public.profiles set blocked=false where id in (t.uid('bx_client'),t.uid('bx_company'));
select t.signup('bx_replacement','bx-replacement@example.ge','{"role":"company","name":"Replacement Owner","company":"Replacement Company","phone":"+995 522 771 005","city":"tbilisi","industry":"leasing"}');
insert into public.offers(request_id,company_id,body,status) values(t.get('bx_request'),t.uid('bx_replacement'),'Replacement chosen offer for this request','chosen');
update public.requests set chosen_offer_id=(select id from public.offers where request_id=t.get('bx_request') and company_id=t.uid('bx_replacement')) where id=t.get('bx_request');
select t.as_user('bx_client');
select t.ok(public.my_company_review_targets(t.uid('bx_replacement'))->0->'rating'='null'::jsonb,'BX previous supplier review not shown as new supplier review');
select public.save_company_review(t.get('bx_request'),3,'Updated experience for the replacement supplier');
select t.as_super();
select t.ok((select company_id=t.uid('bx_replacement') and status='pending' from meetany_private.company_reviews where request_id=t.get('bx_request')),'BX review belongs to the currently chosen company after replacement');
\o
select 'Business feature tests: '||(count(*)-(select n from t.business_start))||' passed' from t.passed;
