\set ON_ERROR_STOP 1
select t.as_anon();
select t.throws('select phone from public.profiles limit 1','42501','FLOW guest phone denied');
select t.throws('select email from public.profiles limit 1','42501','FLOW guest email denied');
select t.lives('select id,company from public.profiles limit 1','FLOW public safe projection survives');
select t.throws($q$select public.log_contact_event('company',t.uid('flow_s'),'reveal','company-profile')$q$,'42501','FLOW guest event denied');
select t.as_user('flow_x');
select t.throws($q$select public.get_deal_contact(t.get('flow_d'))$q$,'MA901','FLOW unrelated contact denied');
select t.throws($q$select public.log_contact_event('company',t.uid('flow_s'),'reveal','company-profile')$q$,'MA901','FLOW unrelated contact logging denied');
select t.as_user('flow_b');
select t.throws('select phone from public.profiles limit 1','42501','FLOW authenticated direct phone denied');
select t.ok(jsonb_array_length(public.get_deal_contact(t.get('flow_d')))=1,'FLOW buyer gets partner only');
select t.ok((public.get_deal_contact(t.get('flow_d'))->0->>'id')::uuid=t.uid('flow_s'),'FLOW partner identity correct');
select t.ok((select count(*) from public.contact_for_request(t.get('flow_r')))=1,'FLOW legacy chosen contact preserved');
select t.lives($q$select public.log_contact_event('company',t.uid('flow_s'),'call','company-profile')$q$,'FLOW selected partner logging works');
select t.as_super();
select t.signup('flow_a','flow-a@test.ge','{"role":"client","name":"Admin","company":"Admin Ltd","phone":"599881004","city":"tbilisi"}');
update public.profiles set role='admin' where id=t.uid('flow_a');
select t.as_user('flow_a');
select t.ok(jsonb_array_length(public.get_deal_contact(t.get('flow_d')))=2,'FLOW admin sees both contacts');
select t.ok((select count(*) from meetany_private.deals where id=t.get('flow_d'))=1,'FLOW admin RLS reads deal');
select t.throws($q$select public.advance_deal(t.get('flow_d'),'cancelled',10)$q$,'MA901','FLOW admin cannot act as a party');
select t.as_super();
insert into public.requests(id,owner_id,title,body,category,city) values(t.put('flow_cancel_r',gen_random_uuid()),t.uid('flow_b'),'Cancel request','Cancellation test body','other','tbilisi');
select t.as_user('flow_s');
select t.put('flow_cancel_o',(public.send_offer(t.get('flow_cancel_r'),'Cancel offer',100,'total',true,5,true)).id);
select t.as_super();
update public.offers set valid_until=current_date-1 where id=t.get('flow_cancel_o');
select t.as_user('flow_b');
select t.throws($q$select public.select_offer_deal(t.get('flow_cancel_o'))$q$,'MA903','FLOW expired offer rejected');
select t.as_super();
update public.offers set valid_until=null where id=t.get('flow_cancel_o');
select t.as_user('flow_b');
-- Legacy choose first: explicitly convert only the same chosen offer, no bulk backfill.
select public.choose_offer(t.get('flow_cancel_o'));
select t.put('flow_cancel_d',(public.select_offer_deal(t.get('flow_cancel_o'))->>'id')::uuid);
select t.ok((public.get_deal(t.get('flow_cancel_d'))->>'stage')='selected','FLOW legacy choice converts explicitly');
select public.advance_deal(t.get('flow_cancel_d'),'cancelled',1);
select t.throws($q$select public.get_deal_contact(t.get('flow_cancel_d'))$q$,'MA901','FLOW cancellation locks contact');
select t.ok((select count(*) from public.contact_for_request(t.get('flow_cancel_r')))=0,'FLOW legacy API cannot bypass cancellation');
select t.throws($q$select public.select_offer_deal(t.get('flow_cancel_o'))$q$,'MA903','FLOW cancelled choice cannot restart');
select t.as_user('flow_a');
select t.ok(jsonb_array_length(public.get_deal_contact(t.get('flow_cancel_d')))=2,'FLOW admin can inspect cancelled contacts');
select t.as_super();
select t.ok(not has_table_privilege('authenticated','meetany_private.deals','UPDATE'),'FLOW direct deal mutation denied');
select t.ok(not has_table_privilege('authenticated','meetany_private.deal_events','SELECT'),'FLOW direct event access denied');
select t.ok(not has_function_privilege('authenticated','meetany_private.deal_event(meetany_private.deals,text)','EXECUTE'),'FLOW private event writer denied');
select t.ok(not exists(select 1 from pg_proc p where pronamespace='public'::regnamespace and proname in ('get_deal','select_offer_deal','propose_deal_terms','confirm_deal_terms','advance_deal','rate_deal','get_deal_contact') and (not prosecdef or not ('search_path=""'=any(proconfig)))),'FLOW RPCs pin empty search path');
