\set ON_ERROR_STOP 1
select t.as_user('flow_b');
select t.put('flow_d',(public.select_offer_deal(t.get('flow_o'))->>'id')::uuid);
select t.ok((public.select_offer_deal(t.get('flow_o'))->>'id')::uuid=t.get('flow_d'),'FLOW selection retry returns same deal');
select t.ok((select chosen_offer_id=t.get('flow_o') from public.requests where id=t.get('flow_r')),'FLOW existing choice updated');
select t.throws($q$select public.advance_deal(t.get('flow_d'),'complete',1)$q$,'MA903','FLOW cannot skip stages');
select public.advance_deal(t.get('flow_d'),'discuss',1);
select public.propose_deal_terms(t.get('flow_d'),2,100,10,'pcs',5,current_date+5,'Tbilisi','50/50',array['VAT']);
select t.throws($q$select public.advance_deal(t.get('flow_d'),'progress',3)$q$,'MA905','FLOW both confirmations required');
select public.confirm_deal_terms(t.get('flow_d'),3);
select t.as_user('flow_s');
select t.throws($q$select public.confirm_deal_terms(t.get('flow_d'),3)$q$,'MA904','FLOW stale confirmation rejected');
select public.propose_deal_terms(t.get('flow_d'),4,110,10,'pcs',5,current_date+5,'Tbilisi','50/50',array['VAT']);
select t.ok((public.get_deal(t.get('flow_d'))->>'buyer_confirmed_at') is null,'FLOW changed terms clear buyer confirmation');
select public.confirm_deal_terms(t.get('flow_d'),5);
select t.as_user('flow_b');
select public.confirm_deal_terms(t.get('flow_d'),6);
select public.advance_deal(t.get('flow_d'),'progress',7);
select t.as_user('flow_s');
select t.throws($q$select public.advance_deal(t.get('flow_d'),'complete',8)$q$,'MA906','FLOW supplier cannot complete');
select t.throws($q$select public.propose_deal_terms(t.get('flow_d'),8,120,10,'pcs',5,null,'Tbilisi','50/50','{}')$q$,'MA903','FLOW progress freezes terms');
select t.as_user('flow_x');
select t.ok((select count(*) from meetany_private.deals where id=t.get('flow_d'))=0,'FLOW unrelated RLS hides deal');
select t.throws($q$select public.get_deal(t.get('flow_d'))$q$,'MA901','FLOW unrelated RPC denied');
select t.as_user('flow_b');
select public.advance_deal(t.get('flow_d'),'complete',8);
select public.rate_deal(t.get('flow_d'),5,'Good',9);
select t.throws($q$select public.rate_deal(t.get('flow_d'),4,'Again',10)$q$,'MA903','FLOW rating immutable');
select t.ok((public.get_deal(t.get('flow_d'))->>'rating')::integer=5,'FLOW rating saved privately');
select t.as_super();
select t.ok((select count(*) from meetany_private.deal_events where deal_id=t.get('flow_d'))=10,'FLOW each revision audited');
select t.ok(exists(select 1 from meetany_private.notifications where user_id=t.uid('flow_s') and offer_id=t.get('flow_o') and read_at is null),'FLOW notification uses engagement inbox');
update public.profiles set blocked=true where id=t.uid('flow_x');
select t.as_user('flow_x');
select t.throws($q$select public.get_deal(t.get('flow_d'))$q$,'MA002','FLOW blocked caller denied');
select t.as_super();
update public.profiles set blocked=false where id=t.uid('flow_x');
