\set ON_ERROR_STOP 1
\o /dev/null
select t.as_super();
create table t.messaging_start as select count(*) n from t.passed;
select t.signup('msg_client','msg-client@example.test','{"role":"client","name":"Message Client","phone":"+995 591 972 001","city":"tbilisi"}');
select t.signup('msg_company','msg-company@example.test','{"role":"company","name":"Message Supplier","company":"Message Company","industry":"furniture","phone":"+995 591 972 002","city":"tbilisi"}');
select t.signup('msg_other','msg-other@example.test','{"role":"client","name":"Message Outsider","phone":"+995 591 972 003","city":"tbilisi"}');
select t.as_anon();
select t.throws($$select public.start_conversation(t.uid('msg_company'))$$,'42501','M anonymous cannot start');
select t.throws($$select * from meetany_private.messages$$,'42501','M anonymous table closed');
select t.as_user('msg_client');
select t.put('msg_general',(public.start_conversation(t.uid('msg_company'))->>'id')::uuid);
select t.ok((public.start_conversation(t.uid('msg_company'))->>'id')::uuid=t.get('msg_general'),'M start idempotent');
select t.ok(public.list_messages(t.get('msg_general'))='[]'::jsonb,'M empty messages');
select t.ok(public.unread_message_count()=0,'M initially no unread');
select t.ok(jsonb_array_length(public.list_my_conversations())=1,'M lists own conversation');
select t.ok(public.list_my_conversations()->0->>'other_id'=t.uid('msg_company')::text,'M other participant identity');
select t.throws($$select public.start_conversation(t.uid('msg_other'))$$,'MA502','M target must be company');
select t.throws($$select * from meetany_private.conversations$$,'42501','M participant table closed');
select t.throws($$insert into meetany_private.messages(conversation_id,sender_id,body) values(t.get('msg_general'),t.uid('msg_client'),'spoof')$$,'42501','M direct write closed');
select t.throws($$select meetany_private.require_conversation(t.get('msg_general'),t.uid('msg_client'))$$,'42501','M private helper closed');
select t.throws($$select public.send_message(t.get('msg_general'),'')$$,'MA505','M empty body');
select t.throws($$select public.send_message(t.get('msg_general'),E' \n\t ')$$,'MA505','M whitespace body');
select t.throws($$select public.send_message(t.get('msg_general'),null)$$,'MA505','M null body');
select t.throws($$select public.send_message(t.get('msg_general'),repeat('ა',2001))$$,'MA505','M long body');
select t.put('msg_first',(public.send_message(t.get('msg_general'),E' \nგამარჯობა\t ')->>'id')::uuid);
select t.ok(public.list_messages(t.get('msg_general'))->0->>'body'='გამარჯობა','M body trimmed');
select t.ok(public.unread_message_count()=0,'M sender not unread');
select t.ok((public.mark_read(t.get('msg_general'))->>'marked')::int=0,'M sender cannot mark outgoing read');
select t.throws($$select public.send_message(t.get('msg_general'),'too fast')$$,'MA506','M two second limit');
select t.ok(jsonb_array_length(public.list_messages(t.get('msg_general'),(public.list_messages(t.get('msg_general'))->0->>'created_at')::timestamptz))=0,'M after excludes timestamp');
select t.throws($$select public.list_messages(t.get('msg_general'),'infinity')$$,'22023','M invalid polling timestamp');
select t.as_user('msg_company');
select t.throws($$select public.start_conversation(t.uid('msg_company'))$$,'MA503','M self denied');
select t.ok(public.unread_message_count()=1,'M receiver unread one');
select t.ok((public.list_my_conversations()->0->>'unread_count')::int=1,'M list unread');
select t.ok(public.list_my_conversations()->0->'last_message'->>'body'='გამარჯობა','M last message');
select t.ok((public.mark_read(t.get('msg_general'))->>'marked')::int=1,'M receiver marks read');
select t.ok(public.unread_message_count()=0,'M receiver unread cleared');
select t.ok(public.list_messages(t.get('msg_general'))->0->>'read_at' is not null,'M receipt set');
select t.ok(public.list_my_conversations()->0->>'company_last_read_at' is not null,'M company read timestamp');
select t.ok(public.list_my_conversations()->0->>'client_last_read_at' is not null,'M client read timestamp');
select t.ok((public.mark_read(t.get('msg_general'))->>'marked')::int=0,'M mark idempotent');
select t.lives($$select public.send_message(t.get('msg_general'),repeat('ა',2000))$$,'M unicode limit and opposite sender independent');
select t.as_user('msg_other');
select t.ok(public.list_my_conversations()='[]'::jsonb,'M outsider list empty');
select t.ok(public.unread_message_count()=0,'M outsider unread empty');
select t.throws($$select public.list_messages(t.get('msg_general'))$$,'MA501','M outsider read denied');
select t.throws($$select public.send_message(t.get('msg_general'),'outsider')$$,'MA501','M outsider write denied');
select t.throws($$select public.mark_read(t.get('msg_general'))$$,'MA501','M outsider mark denied');
select t.throws($$select public.list_messages(gen_random_uuid())$$,'MA501','M missing same as unauthorized');
select t.throws($$select public.admin_list_conversations()$$,'MA003','M regular admin list denied');
select t.throws($$select public.admin_conversation_messages(t.get('msg_general'))$$,'MA003','M regular admin messages denied');
select t.throws($$select public.admin_message_stats()$$,'MA003','M regular admin stats denied');
select t.as_super();
update public.profiles set blocked=true where id=t.uid('msg_client');
select t.as_user('msg_client');
select t.throws($$select public.send_message(t.get('msg_general'),'blocked')$$,'MA002','M blocked send denied');
select t.throws($$select public.start_conversation(t.uid('msg_company'))$$,'MA002','M blocked start denied');
select t.as_super();
update public.profiles set blocked=false where id=t.uid('msg_client');
update meetany_private.messages set created_at=clock_timestamp()-interval '3 seconds' where id=t.get('msg_first');
select t.as_user('msg_client');
select t.lives($$select public.send_message(t.get('msg_general'),'after cooldown')$$,'M cooldown expires');
select t.put('msg_request',(public.create_request('Messaging request','Detailed messaging request','furniture','tbilisi')).id);
select t.as_user('msg_company');
select t.put('msg_context',(public.start_conversation(t.uid('msg_company'),t.get('msg_request'))->>'id')::uuid);
select t.ok(t.get('msg_context')<>t.get('msg_general'),'M separate request context');
select t.ok(public.start_conversation(t.uid('msg_company'),t.get('msg_request'))->>'client_id'=t.uid('msg_client')::text,'M company starts with request owner');
select t.as_user('msg_client');
select t.ok(public.start_conversation(t.uid('msg_company'),t.get('msg_request'))->>'id'=t.get('msg_context')::text,'M both initiators same conversation');
select t.as_user('msg_other');
select t.throws($$select public.start_conversation(t.uid('msg_company'),t.get('msg_request'))$$,'MA504','M outsider cannot bind request');
select t.as_super();
update meetany_private.messages set created_at=clock_timestamp()-interval '10 seconds' where sender_id=t.uid('msg_client');
insert into meetany_private.messages(conversation_id,sender_id,body,created_at)
select t.get('msg_general'),t.uid('msg_client'),'cap fixture',clock_timestamp()-interval '10 seconds' from generate_series(1,18);
select t.as_user('msg_client');
select t.throws($$select public.send_message(t.get('msg_context'),'global cap')$$,'MA506','M 20 minute cap across conversations');
select t.as_super();
update meetany_private.messages set created_at=clock_timestamp()-interval '61 seconds' where sender_id=t.uid('msg_client');
select t.as_user('msg_client');
select t.lives($$select public.send_message(t.get('msg_context'),'new minute')$$,'M minute cap expires');
select t.ok(jsonb_array_length(public.list_messages(t.get('msg_context'),clock_timestamp()-interval '1 minute'))=1,'M polling later messages');
select t.ok(public.list_my_conversations()->0->>'id'=t.get('msg_context')::text,'M newest conversation first');
select t.as_super();
select t.throws($$update meetany_private.conversations set context_key='general' where id=t.get('msg_context')$$,'MA507','M immutable context');
select t.as_user('msg_client');
select t.put('msg_request_gone',(public.create_request('Deleted messaging request','Request deleted with its conversation','furniture','tbilisi')).id);
select t.put('msg_gone',(public.start_conversation(t.uid('msg_company'),t.get('msg_request_gone'))->>'id')::uuid);
select t.as_super();
delete from public.requests where id=t.get('msg_request_gone');
select t.ok(not exists(select 1 from meetany_private.conversations where id=t.get('msg_gone')),'M deleted request removes its conversation');
select t.ok((select request_id=t.get('msg_request') from meetany_private.conversations where id=t.get('msg_context')),'M other request context kept');
select t.as_user('msg_client');
select t.ok(public.start_conversation(t.uid('msg_company'))->>'id'=t.get('msg_general')::text,'M deleted request not merged');
select t.ok(jsonb_array_length(public.list_messages(t.get('msg_context')))=1,'M request context readable');
select t.as_user('admin');
select t.ok((public.admin_list_conversations()->>'filteredTotal')::int=2,'M admin sees all');
select t.ok((public.admin_conversation_messages(t.get('msg_context'))->>'filteredTotal')::int=1,'M admin reads messages');
select t.ok((public.admin_message_stats()->'totals'->'day'->>'conversations')::int=2,'M stats day');
select t.ok((public.admin_message_stats()->'totals'->'week'->>'messages')::int=22,'M stats week');
select t.ok((public.admin_message_stats()->'totals'->'month'->>'messages')::int=22,'M stats month');
select t.throws($$select public.admin_list_conversations('{}')$$,'22023','M bad list cursor');
select t.throws($$select public.admin_conversation_messages(t.get('msg_context'),'{}')$$,'22023','M bad message cursor');
select t.as_super();
insert into meetany_private.messages(conversation_id,sender_id,body) select t.get('msg_context'),t.uid('msg_client'),'page fixture' from generate_series(1,30);
insert into meetany_private.conversations(client_id,company_id,context_key)
select t.uid('msg_client'),t.uid('msg_company'),gen_random_uuid()::text from generate_series(1,30);
select t.as_user('admin');
do $$ declare page jsonb; cur jsonb; seen uuid[]:='{}'; item jsonb; begin
 loop
  page:=public.admin_list_conversations(cur);
  for item in select * from jsonb_array_elements(page->'items') loop
   perform t.ok(not (item->>'id')::uuid=any(seen),'M conversation cursor unique');
   seen:=array_append(seen,(item->>'id')::uuid);
  end loop;
  exit when not (page->>'hasMore')::boolean;
  cur:=page->'nextCursor';
 end loop;
 perform t.ok(cardinality(seen)=32,'M conversation traversal complete');
 seen:='{}';cur:=null;
 loop
  page:=public.admin_conversation_messages(t.get('msg_context'),cur);
  for item in select * from jsonb_array_elements(page->'items') loop
   perform t.ok(not (item->>'id')::uuid=any(seen),'M message cursor unique');
   seen:=array_append(seen,(item->>'id')::uuid);
  end loop;
  exit when not (page->>'hasMore')::boolean;
  cur:=page->'nextCursor';
 end loop;
 perform t.ok(cardinality(seen)=31,'M message traversal complete');
end $$;
select t.as_super();
select t.ok((select relrowsecurity from pg_class where oid='meetany_private.messages'::regclass),'M messages RLS');
select t.ok((select relrowsecurity from pg_class where oid='meetany_private.conversations'::regclass),'M conversations RLS');
delete from public.profiles where id=t.uid('msg_client');
select t.ok(not exists(select 1 from meetany_private.conversations where company_id=t.uid('msg_company')),'M client delete cascades conversations');
select t.ok(not exists(select 1 from meetany_private.messages where conversation_id in (t.get('msg_general'),t.get('msg_context'))),'M client delete cascades messages');
select t.as_user('msg_other');
select t.put('msg_cascade',(public.start_conversation(t.uid('msg_company'))->>'id')::uuid);
select public.send_message(t.get('msg_cascade'),'company cascade');
select t.as_super();
delete from public.profiles where id=t.uid('msg_company');
select t.ok(not exists(select 1 from meetany_private.conversations where id=t.get('msg_cascade')),'M company delete cascades conversations');
select t.ok(not exists(select 1 from meetany_private.messages where conversation_id=t.get('msg_cascade')),'M company delete cascades messages');
\o
\pset tuples_only on
\pset format unaligned
select format('ALL %s MESSAGING TESTS PASSED',count(*)-(select n from t.messaging_start)) from t.passed;
select format('TOTAL %s SQL ASSERTIONS PASSED',count(*)) from t.passed;
