\set ON_ERROR_STOP 1
\o /dev/null
select t.as_super();
create table t.registration_start as select count(*) n from t.passed;
grant select on t.registration_start to public;
select t.put('ra_session',gen_random_uuid());
select t.put('ra_session_two',gen_random_uuid());
select t.put('ra_event',gen_random_uuid());
select t.as_anon();
select t.throws($q$select public.admin_registration_analytics()$q$,'42501','RA guest cannot read aggregates');
select t.throws($q$select * from meetany_private.registration_events$q$,'42501','RA guest cannot read raw events');
select t.throws($q$select public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'admin','form_open')$q$,'MA801','RA rejects invalid role');
select t.throws($q$select public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'company','arbitrary')$q$,'MA801','RA rejects arbitrary stage');
select t.throws($q$select public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'client','form_submitted')$q$,'MA801','RA requires opened attempt');
select t.ok(public.record_registration_event(t.get('ra_event'),t.get('ra_session'),'client','form_open'),'RA guest can record opened form');
select t.ok(not public.record_registration_event(t.get('ra_event'),t.get('ra_session'),'client','form_open'),'RA same event deduplicates');
select t.ok(not public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'client','form_open'),'RA stage deduplicates with new event ID');
select t.throws($q$select public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'company','form_started')$q$,'MA801','RA attempt role immutable');
select t.ok(public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'client','form_started'),'RA records started');
select t.ok(public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'client','form_submitted'),'RA records submitted');
select t.throws($q$select public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'client','profile_created')$q$,'MA001','RA guest cannot fake completion');
select t.as_super();
select t.signup('ra_user','ra_user@example.ge','{"role":"client","name":"Analytics Test","phone":"+995 555 778 110","city":"tbilisi"}');
select t.as_user('ra_user');
select t.throws($q$select public.admin_registration_analytics()$q$,'MA003','RA client cannot read aggregates');
select t.ok(public.record_registration_event(gen_random_uuid(),t.get('ra_session'),'client','profile_created'),'RA new own profile confirms completion');
select t.ok(public.record_registration_event(gen_random_uuid(),t.get('ra_session_two'),'client','form_open'),'RA second attempt opens');
select t.ok(not public.record_registration_event(gen_random_uuid(),t.get('ra_session_two'),'client','profile_created'),'RA one profile cannot inflate completion across attempts');
select t.as_user('admin');
select t.ok((public.admin_registration_analytics()->>'sessions')::int=2,'RA cohort session count exact');
select t.ok((public.admin_registration_analytics()->>'completed')::int=1,'RA confirmed completion exact');
select t.ok((public.admin_registration_analytics()->>'started')::int=1,'RA starts count actual event');
select t.ok((public.admin_registration_analytics()->>'submitted')::int=1,'RA submission count actual event');
select t.ok((public.admin_registration_analytics()->>'active')::int=1,'RA recent incomplete attempt active');
select t.ok((public.admin_registration_analytics(30,'company')->>'sessions')::int=0,'RA role filter');
select t.throws($q$select public.admin_registration_analytics(365,'all')$q$,'MA801','RA period bounded');
select t.as_super();
update meetany_private.registration_sessions set last_event_at=now()-interval '31 minutes' where id=t.get('ra_session_two');
select t.as_user('admin');
select t.ok((public.admin_registration_analytics()->>'stalled')::int=1,'RA unfinished 30-minute attempt stalled, not completed');
select t.ok((select (value->>'count')::int from jsonb_array_elements(public.admin_registration_analytics()->'lastStages') where value->>'stage'='profile_created')=1,'RA last stage completion exact');
select t.as_super();
update meetany_private.registration_sessions set created_at=now()-interval '25 hours' where id=t.get('ra_session_two');
select t.as_anon();
select t.throws($q$select public.record_registration_event(gen_random_uuid(),t.get('ra_session_two'),'client','form_started')$q$,'MA801','RA expired attempt rejected');
select t.as_super();
delete from public.profiles where id=t.uid('ra_user');
select t.ok((select count(*) from meetany_private.registration_events where stage='profile_created' and profile_id is null)=1,'RA profile removal safely anonymizes completion');
select t.as_user('admin');
select t.ok((public.admin_registration_analytics()->>'completed')::int=1,'RA historical confirmed completion survives profile removal');
select t.ok((public.admin_registration_analytics()->'sources'->0->>'source')='unknown','RA old four-field callers have unknown attribution');
select t.ok((public.admin_registration_analytics()->'devices'->0->>'device')='unknown','RA old callers do not invent device');
select t.as_anon();
select t.throws($q$select public.record_registration_event(gen_random_uuid(),gen_random_uuid(),'company','form_open','https://example.com','mobile')$q$,'MA801','RA source cannot store URL');
select t.throws($q$select public.record_registration_event(gen_random_uuid(),gen_random_uuid(),'company','form_open','request','iPhone')$q$,'MA801','RA device cannot store identifying model');
select t.ok(public.record_registration_event(gen_random_uuid(),gen_random_uuid(),'company','form_open','request','mobile'),'RA bounded source/device stored');
select t.as_user('admin');
select t.ok((select (value->>'sessions')::int from jsonb_array_elements(public.admin_registration_analytics()->'sources') where value->>'source'='request')=1,'RA source totals exact');
select t.ok((select (value->>'sessions')::int from jsonb_array_elements(public.admin_registration_analytics()->'devices') where value->>'device'='mobile')=1,'RA device totals exact');
select t.as_super();
\o
select 'Registration analytics tests: '||(count(*)-(select n from t.registration_start))||' passed' from t.passed;
